welcomer:
  # Main welcome message to be displayed when a player joins the server
  title: "&a&lWelcome!"
  
  # Subtitle message to accompany the main welcome message
  subtitle: "&#949494To my server!"
  
  # Number of ticks the title takes to fade in
  title-fade-in: 10
  
  # Number of ticks the title stays on the screen before fading out
  title-stay: 80
  
  # Number of ticks the title takes to fade out
  title-fade-out: 10

  # Whether to play the join sound
  join-sound: true

  # Sound played upon player join (default: ENTITY_PLAYER_LEVELUP)
  # Set to false to disable
  sound: ENTITY_PLAYER_LEVELUP
